-- Lesson Architect Database Schema (WITHOUT RLS)
-- Run this version if RLS policies are causing issues

-- Schemes of Work table
CREATE TABLE IF NOT EXISTS schemes (
    scheme_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    grade TEXT NOT NULL,
    subject TEXT NOT NULL,
    term TEXT NOT NULL,
    mode TEXT NOT NULL, -- standard, weekly, term, mada
    teacher_id TEXT NOT NULL,
    language TEXT DEFAULT 'english',
    total_weeks INTEGER NOT NULL,
    lessons_per_week INTEGER NOT NULL,
    rows JSONB NOT NULL, -- Array of week content objects
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_schemes_teacher ON schemes(teacher_id);
CREATE INDEX IF NOT EXISTS idx_schemes_grade_subject ON schemes(grade, subject);
CREATE INDEX IF NOT EXISTS idx_schemes_term ON schemes(term);
CREATE INDEX IF NOT EXISTS idx_schemes_created ON schemes(created_at DESC);

-- Lesson Plans table
CREATE TABLE IF NOT EXISTS lesson_plans (
    lesson_plan_id TEXT PRIMARY KEY,
    scheme_id TEXT NOT NULL REFERENCES schemes(scheme_id) ON DELETE CASCADE,
    teacher_id TEXT NOT NULL,
    title TEXT NOT NULL,
    grade TEXT NOT NULL,
    subject TEXT NOT NULL,
    week INTEGER NOT NULL,
    lesson_number INTEGER NOT NULL,
    duration_minutes INTEGER DEFAULT 40,
    learning_outcomes JSONB NOT NULL,
    key_questions JSONB NOT NULL,
    introduction JSONB NOT NULL,
    main_activities JSONB NOT NULL,
    differentiation JSONB NOT NULL,
    assessment JSONB NOT NULL,
    conclusion JSONB NOT NULL,
    teacher_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for lesson plans
CREATE INDEX IF NOT EXISTS idx_lesson_plans_scheme ON lesson_plans(scheme_id);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_teacher ON lesson_plans(teacher_id);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_week ON lesson_plans(week);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_created ON lesson_plans(created_at DESC);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for updated_at
CREATE TRIGGER update_schemes_updated_at BEFORE UPDATE ON schemes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_lesson_plans_updated_at BEFORE UPDATE ON lesson_plans
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE schemes IS 'Stores CBC-compliant schemes of work generated by LessonArchitectAgent';
COMMENT ON TABLE lesson_plans IS 'Stores detailed lesson plans derived from schemes';
COMMENT ON COLUMN schemes.rows IS 'JSONB array of week content with SLOs, KIQs, learning experiences, resources, assessment, reflection';
COMMENT ON COLUMN schemes.mode IS 'Generation mode: standard (full term), weekly (week-by-week), term (overview), mada (Kiswahili 3-week cycles)';

-- NOTE: RLS is NOT enabled in this version
-- This allows the tables to work without authentication issues
-- The backend uses service_role key which bypasses RLS anyway
