-- Lesson Architect Database Schema
-- Tables for storing schemes of work and lesson plans

-- Schemes of Work table
CREATE TABLE IF NOT EXISTS schemes (
    scheme_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    grade TEXT NOT NULL,
    subject TEXT NOT NULL,
    term TEXT NOT NULL,
    mode TEXT NOT NULL, -- standard, weekly, term, mada
    teacher_id TEXT NOT NULL,
    language TEXT DEFAULT 'english',
    total_weeks INTEGER NOT NULL,
    lessons_per_week INTEGER NOT NULL,
    rows JSONB NOT NULL, -- Array of week content objects
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_schemes_teacher ON schemes(teacher_id);
CREATE INDEX IF NOT EXISTS idx_schemes_grade_subject ON schemes(grade, subject);
CREATE INDEX IF NOT EXISTS idx_schemes_term ON schemes(term);
CREATE INDEX IF NOT EXISTS idx_schemes_created ON schemes(created_at DESC);

-- Lesson Plans table
CREATE TABLE IF NOT EXISTS lesson_plans (
    lesson_plan_id TEXT PRIMARY KEY,
    scheme_id TEXT REFERENCES schemes(scheme_id) ON DELETE CASCADE,
    teacher_id TEXT NOT NULL,
    grade TEXT NOT NULL,
    subject TEXT NOT NULL,
    strand TEXT,
    sub_strand TEXT,
    week INTEGER NOT NULL,
    lesson INTEGER NOT NULL DEFAULT 1,
    -- Full validated LessonPlan JSON (scheme-scribe-ai contract).
    -- camelCase keys: title, subStrand, keyInquiryQuestion, introduction{},
    -- development{}, conclusion{}, assessment[], differentiation{},
    -- resources[], teacherReflection, etc. See agents/scheme/lesson_plan.py.
    plan JSONB NOT NULL,
    -- Legacy typed columns kept nullable for back-compat with old readers.
    -- New inserts do not populate these. Remove once no readers reference them.
    title TEXT,
    lesson_number INTEGER,
    duration_minutes INTEGER DEFAULT 40,
    learning_outcomes JSONB,
    key_questions JSONB,
    introduction JSONB,
    main_activities JSONB,
    differentiation JSONB,
    assessment JSONB,
    conclusion JSONB,
    teacher_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for lesson plans
CREATE INDEX IF NOT EXISTS idx_lesson_plans_scheme ON lesson_plans(scheme_id);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_teacher ON lesson_plans(teacher_id);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_week ON lesson_plans(week);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_created ON lesson_plans(created_at DESC);

-- Row Level Security (RLS) for multi-tenancy
ALTER TABLE schemes ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_plans ENABLE ROW LEVEL SECURITY;

-- RLS Policies for schemes
CREATE POLICY "Teachers can view their own schemes"
    ON schemes FOR SELECT
    USING (auth.uid()::text = teacher_id);

CREATE POLICY "Teachers can insert their own schemes"
    ON schemes FOR INSERT
    WITH CHECK (auth.uid()::text = teacher_id);

CREATE POLICY "Teachers can update their own schemes"
    ON schemes FOR UPDATE
    USING (auth.uid()::text = teacher_id);

CREATE POLICY "Teachers can delete their own schemes"
    ON schemes FOR DELETE
    USING (auth.uid()::text = teacher_id);

-- RLS Policies for lesson plans
CREATE POLICY "Teachers can view their own lesson plans"
    ON lesson_plans FOR SELECT
    USING (auth.uid()::text = teacher_id);

CREATE POLICY "Teachers can insert their own lesson plans"
    ON lesson_plans FOR INSERT
    WITH CHECK (auth.uid()::text = teacher_id);

CREATE POLICY "Teachers can update their own lesson plans"
    ON lesson_plans FOR UPDATE
    USING (auth.uid()::text = teacher_id);

CREATE POLICY "Teachers can delete their own lesson plans"
    ON lesson_plans FOR DELETE
    USING (auth.uid()::text = teacher_id);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for updated_at
CREATE TRIGGER update_schemes_updated_at BEFORE UPDATE ON schemes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_lesson_plans_updated_at BEFORE UPDATE ON lesson_plans
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE schemes IS 'Stores CBC-compliant schemes of work generated by LessonArchitectAgent';
COMMENT ON TABLE lesson_plans IS 'Stores detailed lesson plans derived from schemes';
COMMENT ON COLUMN schemes.rows IS 'JSONB array of week content with SLOs, KIQs, learning experiences, resources, assessment, reflection';
COMMENT ON COLUMN schemes.mode IS 'Generation mode: standard (full term), weekly (week-by-week), term (overview), mada (Kiswahili 3-week cycles)';
